#!/usr/bin/env bash

[ -x "$(command -v exa)" ] && alias ls='exa --icons --color-scale'
alias ll='ls -lah'
alias la='ls -a'

if [ -x "$(command -v exa)" ]; then
  alias gls='ll --git'
  alias llz='ll --sort=size'
  alias lla='ll --sort=acc'
  alias llc='ll --sort=cr'
  alias tree='exa -aT --color=always --group-directories-first --icons --ignore-glob=".git|node_modules"'
  alias l.='exa -a | rg "^\."'
fi
