"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
read_only = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[shell]
disabled = false