#!/usr/bin/env bash

gdv() {
  git diff -w "$@" | view -
}

git_current_branch() {
  git -C "$1" branch | sed '/^\*/!d;s/\* //'
}

git_work_in_progress() {
  if $(git log -n 1 2>/dev/null | grep -q -c "\-\-wip\-\-"); then
    echo "WIP!!"  
  fi
}

ggf() {
  [[ "$#" != 1 ]] && local b="$(git_current_branch)"
  git push --force origin "${b:=$1}"
}

ggl() {
  if [[ "$#" != 0 ]] && [[ "$#" != 1 ]]; then
    git pull origin "${*}"  
  else
    [[ "$#" == 0 ]] && local b="$(git_current_branch)"
    git pull origin "${b:=$1}"
  fi
}

ggp() {
  if [[ "$#" != 0 ]] && [[ "$#" != 1 ]]; then
    git push origin "${*}"  
  else
    [[ "$#" == 0 ]] && local b="$(git_current_branch)"
    git push origin "${b:=$1}"
  fi
}

ggpnp() {
  if [[ "$#" == 0 ]]; then
    ggl && ggp
  else
    ggl "${*}" && ggp "${*}"
  fi
}

ggu() {
  [[ "$#" != 0 ]] && local b="$(git_current_branch)"
  git pull --rebase origin "${b:=$1}"
}

__git_log_prettily() {
  if ! [ -z $1 ]; then
    git log --pretty=$1  
  fi
}